# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)



DESCRIPTOR = descriptor.FileDescriptor(
  name='offline_tree.proto',
  package='util',
  serialized_pb='\n\x12offline_tree.proto\x12\x04util\"&\n\nIdCodePair\x12\n\n\x02id\x18\x01 \x02(\x03\x12\x0c\n\x04\x63ode\x18\x02 \x02(\x03\"E\n\nIdCodePart\x12\x0f\n\x07part_id\x18\x01 \x02(\x0c\x12&\n\x0cid_code_list\x18\x02 \x03(\x0b\x32\x10.util.IdCodePair\"3\n\x08TreeMeta\x12\x11\n\tmax_level\x18\x01 \x02(\x05\x12\x14\n\x0cid_code_part\x18\x02 \x03(\x0c\"m\n\x04Node\x12\n\n\x02id\x18\x01 \x02(\x03\x12\x11\n\tprobality\x18\x02 \x02(\x02\x12\x14\n\x0cleaf_cate_id\x18\x03 \x02(\x05\x12\x0f\n\x07is_leaf\x18\x04 \x02(\x08\x12\x11\n\tembed_vec\x18\x05 \x03(\x02\x12\x0c\n\x04\x64\x61ta\x18\x06 \x01(\x0c\"$\n\x06KVItem\x12\x0b\n\x03key\x18\x01 \x02(\x0c\x12\r\n\x05value\x18\x02 \x02(\x0c')




_IDCODEPAIR = descriptor.Descriptor(
  name='IdCodePair',
  full_name='util.IdCodePair',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='id', full_name='util.IdCodePair.id', index=0,
      number=1, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='code', full_name='util.IdCodePair.code', index=1,
      number=2, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=28,
  serialized_end=66,
)


_IDCODEPART = descriptor.Descriptor(
  name='IdCodePart',
  full_name='util.IdCodePart',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='part_id', full_name='util.IdCodePart.part_id', index=0,
      number=1, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='id_code_list', full_name='util.IdCodePart.id_code_list', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=68,
  serialized_end=137,
)


_TREEMETA = descriptor.Descriptor(
  name='TreeMeta',
  full_name='util.TreeMeta',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='max_level', full_name='util.TreeMeta.max_level', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='id_code_part', full_name='util.TreeMeta.id_code_part', index=1,
      number=2, type=12, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=139,
  serialized_end=190,
)


_NODE = descriptor.Descriptor(
  name='Node',
  full_name='util.Node',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='id', full_name='util.Node.id', index=0,
      number=1, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='probality', full_name='util.Node.probality', index=1,
      number=2, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='leaf_cate_id', full_name='util.Node.leaf_cate_id', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='is_leaf', full_name='util.Node.is_leaf', index=3,
      number=4, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='embed_vec', full_name='util.Node.embed_vec', index=4,
      number=5, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='data', full_name='util.Node.data', index=5,
      number=6, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=192,
  serialized_end=301,
)


_KVITEM = descriptor.Descriptor(
  name='KVItem',
  full_name='util.KVItem',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='key', full_name='util.KVItem.key', index=0,
      number=1, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='value', full_name='util.KVItem.value', index=1,
      number=2, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=303,
  serialized_end=339,
)

_IDCODEPART.fields_by_name['id_code_list'].message_type = _IDCODEPAIR
DESCRIPTOR.message_types_by_name['IdCodePair'] = _IDCODEPAIR
DESCRIPTOR.message_types_by_name['IdCodePart'] = _IDCODEPART
DESCRIPTOR.message_types_by_name['TreeMeta'] = _TREEMETA
DESCRIPTOR.message_types_by_name['Node'] = _NODE
DESCRIPTOR.message_types_by_name['KVItem'] = _KVITEM

class IdCodePair(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _IDCODEPAIR
  
  # @@protoc_insertion_point(class_scope:util.IdCodePair)

class IdCodePart(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _IDCODEPART
  
  # @@protoc_insertion_point(class_scope:util.IdCodePart)

class TreeMeta(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _TREEMETA
  
  # @@protoc_insertion_point(class_scope:util.TreeMeta)

class Node(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _NODE
  
  # @@protoc_insertion_point(class_scope:util.Node)

class KVItem(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _KVITEM
  
  # @@protoc_insertion_point(class_scope:util.KVItem)

# @@protoc_insertion_point(module_scope)
