# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)



DESCRIPTOR = descriptor.FileDescriptor(
  name='online_tree.proto',
  package='tdm_serving',
  serialized_pb='\n\x11online_tree.proto\x12\x0btdm_serving\"\x86\x01\n\x06UINode\x12\x0b\n\x03seq\x18\x01 \x02(\x05\x12\n\n\x02id\x18\x02 \x01(\x06\x12\r\n\x05level\x18\x03 \x02(\x05\x12\x0e\n\x06parent\x18\x04 \x01(\x05\x12\x10\n\x08\x63hildren\x18\x05 \x03(\x05\x12\x0c\n\x04\x64\x61ta\x18\x06 \x03(\x02\x12\x14\n\x0cleaf_cate_id\x18\x07 \x01(\x05\x12\x0e\n\x06hashid\x18\x08 \x01(\x06\"(\n\x07UILevel\x12\x0e\n\x06offset\x18\x01 \x02(\x05\x12\r\n\x05\x63ount\x18\x02 \x02(\x05\"Z\n\x06UIHead\x12\x0b\n\x03tid\x18\x01 \x01(\x05\x12\x0e\n\x06offset\x18\x02 \x01(\x05\x12\r\n\x05\x63ount\x18\x03 \x01(\x05\x12$\n\x06levels\x18\x04 \x03(\x0b\x32\x14.tdm_serving.UILevel\"O\n\x06UITree\x12\"\n\x05nodes\x18\x01 \x03(\x0b\x32\x13.tdm_serving.UINode\x12!\n\x04head\x18\x02 \x01(\x0b\x32\x13.tdm_serving.UIHead\",\n\x06UIMeta\x12\"\n\x05heads\x18\x01 \x03(\x0b\x32\x13.tdm_serving.UIHead')




_UINODE = descriptor.Descriptor(
  name='UINode',
  full_name='tdm_serving.UINode',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='seq', full_name='tdm_serving.UINode.seq', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='id', full_name='tdm_serving.UINode.id', index=1,
      number=2, type=6, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='level', full_name='tdm_serving.UINode.level', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='parent', full_name='tdm_serving.UINode.parent', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='children', full_name='tdm_serving.UINode.children', index=4,
      number=5, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='data', full_name='tdm_serving.UINode.data', index=5,
      number=6, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='leaf_cate_id', full_name='tdm_serving.UINode.leaf_cate_id', index=6,
      number=7, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='hashid', full_name='tdm_serving.UINode.hashid', index=7,
      number=8, type=6, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=35,
  serialized_end=169,
)


_UILEVEL = descriptor.Descriptor(
  name='UILevel',
  full_name='tdm_serving.UILevel',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='offset', full_name='tdm_serving.UILevel.offset', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='count', full_name='tdm_serving.UILevel.count', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=171,
  serialized_end=211,
)


_UIHEAD = descriptor.Descriptor(
  name='UIHead',
  full_name='tdm_serving.UIHead',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='tid', full_name='tdm_serving.UIHead.tid', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='offset', full_name='tdm_serving.UIHead.offset', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='count', full_name='tdm_serving.UIHead.count', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='levels', full_name='tdm_serving.UIHead.levels', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=213,
  serialized_end=303,
)


_UITREE = descriptor.Descriptor(
  name='UITree',
  full_name='tdm_serving.UITree',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='nodes', full_name='tdm_serving.UITree.nodes', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='head', full_name='tdm_serving.UITree.head', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=305,
  serialized_end=384,
)


_UIMETA = descriptor.Descriptor(
  name='UIMeta',
  full_name='tdm_serving.UIMeta',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='heads', full_name='tdm_serving.UIMeta.heads', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=386,
  serialized_end=430,
)

_UIHEAD.fields_by_name['levels'].message_type = _UILEVEL
_UITREE.fields_by_name['nodes'].message_type = _UINODE
_UITREE.fields_by_name['head'].message_type = _UIHEAD
_UIMETA.fields_by_name['heads'].message_type = _UIHEAD
DESCRIPTOR.message_types_by_name['UINode'] = _UINODE
DESCRIPTOR.message_types_by_name['UILevel'] = _UILEVEL
DESCRIPTOR.message_types_by_name['UIHead'] = _UIHEAD
DESCRIPTOR.message_types_by_name['UITree'] = _UITREE
DESCRIPTOR.message_types_by_name['UIMeta'] = _UIMETA

class UINode(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _UINODE
  
  # @@protoc_insertion_point(class_scope:tdm_serving.UINode)

class UILevel(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _UILEVEL
  
  # @@protoc_insertion_point(class_scope:tdm_serving.UILevel)

class UIHead(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _UIHEAD
  
  # @@protoc_insertion_point(class_scope:tdm_serving.UIHead)

class UITree(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _UITREE
  
  # @@protoc_insertion_point(class_scope:tdm_serving.UITree)

class UIMeta(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _UIMETA
  
  # @@protoc_insertion_point(class_scope:tdm_serving.UIMeta)

# @@protoc_insertion_point(module_scope)
