#!/bin/sh
if [ $# -lt 2 ]; then
    echo "usage: $0 net_type model_path svg_name"
    exit -1
fi
set -x
dirpath=`dirname $0`

model_path=$1
shift
svg_name=$1
shift

python ${dirpath}/blaze_drawer.py --input ${model_path} --output ${svg_name}.dot --embed_docstring
dot -Tsvg ${svg_name}.dot -o ${svg_name}.svg
rm ${svg_name}.dot

