# Copyright (C) 2016-2018 Alibaba Group Holding Limited
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
#     http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ==============================================================================

# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tree.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='tree.proto',
  package='tdm',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\ntree.proto\x12\x03tdm\"&\n\nIdCodePair\x12\n\n\x02id\x18\x01 \x02(\x03\x12\x0c\n\x04\x63ode\x18\x02 \x02(\x03\"D\n\nIdCodePart\x12\x0f\n\x07part_id\x18\x01 \x02(\x0c\x12%\n\x0cid_code_list\x18\x02 \x03(\x0b\x32\x0f.tdm.IdCodePair\"3\n\x08TreeMeta\x12\x11\n\tmax_level\x18\x01 \x02(\x05\x12\x14\n\x0cid_code_part\x18\x02 \x03(\x0c\"m\n\x04Node\x12\n\n\x02id\x18\x01 \x02(\x03\x12\x11\n\tprobality\x18\x02 \x02(\x02\x12\x14\n\x0cleaf_cate_id\x18\x03 \x02(\x05\x12\x0f\n\x07is_leaf\x18\x04 \x02(\x08\x12\x11\n\tembed_vec\x18\x05 \x03(\x02\x12\x0c\n\x04\x64\x61ta\x18\x06 \x01(\x0c')
)




_IDCODEPAIR = _descriptor.Descriptor(
  name='IdCodePair',
  full_name='tdm.IdCodePair',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='tdm.IdCodePair.id', index=0,
      number=1, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='code', full_name='tdm.IdCodePair.code', index=1,
      number=2, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=19,
  serialized_end=57,
)


_IDCODEPART = _descriptor.Descriptor(
  name='IdCodePart',
  full_name='tdm.IdCodePart',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='part_id', full_name='tdm.IdCodePart.part_id', index=0,
      number=1, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='id_code_list', full_name='tdm.IdCodePart.id_code_list', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=59,
  serialized_end=127,
)


_TREEMETA = _descriptor.Descriptor(
  name='TreeMeta',
  full_name='tdm.TreeMeta',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='max_level', full_name='tdm.TreeMeta.max_level', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='id_code_part', full_name='tdm.TreeMeta.id_code_part', index=1,
      number=2, type=12, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=129,
  serialized_end=180,
)


_NODE = _descriptor.Descriptor(
  name='Node',
  full_name='tdm.Node',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='tdm.Node.id', index=0,
      number=1, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='probality', full_name='tdm.Node.probality', index=1,
      number=2, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='leaf_cate_id', full_name='tdm.Node.leaf_cate_id', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='is_leaf', full_name='tdm.Node.is_leaf', index=3,
      number=4, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='embed_vec', full_name='tdm.Node.embed_vec', index=4,
      number=5, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data', full_name='tdm.Node.data', index=5,
      number=6, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=182,
  serialized_end=291,
)

_IDCODEPART.fields_by_name['id_code_list'].message_type = _IDCODEPAIR
DESCRIPTOR.message_types_by_name['IdCodePair'] = _IDCODEPAIR
DESCRIPTOR.message_types_by_name['IdCodePart'] = _IDCODEPART
DESCRIPTOR.message_types_by_name['TreeMeta'] = _TREEMETA
DESCRIPTOR.message_types_by_name['Node'] = _NODE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

IdCodePair = _reflection.GeneratedProtocolMessageType('IdCodePair', (_message.Message,), dict(
  DESCRIPTOR = _IDCODEPAIR,
  __module__ = 'tree_pb2'
  # @@protoc_insertion_point(class_scope:tdm.IdCodePair)
  ))
_sym_db.RegisterMessage(IdCodePair)

IdCodePart = _reflection.GeneratedProtocolMessageType('IdCodePart', (_message.Message,), dict(
  DESCRIPTOR = _IDCODEPART,
  __module__ = 'tree_pb2'
  # @@protoc_insertion_point(class_scope:tdm.IdCodePart)
  ))
_sym_db.RegisterMessage(IdCodePart)

TreeMeta = _reflection.GeneratedProtocolMessageType('TreeMeta', (_message.Message,), dict(
  DESCRIPTOR = _TREEMETA,
  __module__ = 'tree_pb2'
  # @@protoc_insertion_point(class_scope:tdm.TreeMeta)
  ))
_sym_db.RegisterMessage(TreeMeta)

Node = _reflection.GeneratedProtocolMessageType('Node', (_message.Message,), dict(
  DESCRIPTOR = _NODE,
  __module__ = 'tree_pb2'
  # @@protoc_insertion_point(class_scope:tdm.Node)
  ))
_sym_db.RegisterMessage(Node)


# @@protoc_insertion_point(module_scope)
