# Copyright (C) 2016-2018 Alibaba Group Holding Limited
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
#     http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ==============================================================================

# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.8
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.





from sys import version_info
if version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_dist_tree_api', [dirname(__file__)])
        except ImportError:
            import _dist_tree_api
            return _dist_tree_api
        if fp is not None:
            try:
                _mod = imp.load_module('_dist_tree_api', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _dist_tree_api = swig_import_helper()
    del swig_import_helper
else:
    import _dist_tree_api
del version_info
try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.


def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if (name == "thisown"):
        return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if (not static):
        if _newclass:
            object.__setattr__(self, name, value)
        else:
            self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr_nondynamic(self, class_type, name, static=1):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    if (not static):
        return object.__getattr__(self, name)
    else:
        raise AttributeError(name)

def _swig_getattr(self, class_type, name):
    return _swig_getattr_nondynamic(self, class_type, name, 0)


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object:
        pass
    _newclass = 0



def cdata(ptr, nelements=1):
    return _dist_tree_api.cdata(ptr, nelements)
cdata = _dist_tree_api.cdata

def memmove(data, indata):
    return _dist_tree_api.memmove(data, indata)
memmove = _dist_tree_api.memmove
class SwigPyIterator(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, SwigPyIterator, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, SwigPyIterator, name)

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _dist_tree_api.delete_SwigPyIterator
    __del__ = lambda self: None

    def value(self):
        return _dist_tree_api.SwigPyIterator_value(self)

    def incr(self, n=1):
        return _dist_tree_api.SwigPyIterator_incr(self, n)

    def decr(self, n=1):
        return _dist_tree_api.SwigPyIterator_decr(self, n)

    def distance(self, x):
        return _dist_tree_api.SwigPyIterator_distance(self, x)

    def equal(self, x):
        return _dist_tree_api.SwigPyIterator_equal(self, x)

    def copy(self):
        return _dist_tree_api.SwigPyIterator_copy(self)

    def next(self):
        return _dist_tree_api.SwigPyIterator_next(self)

    def __next__(self):
        return _dist_tree_api.SwigPyIterator___next__(self)

    def previous(self):
        return _dist_tree_api.SwigPyIterator_previous(self)

    def advance(self, n):
        return _dist_tree_api.SwigPyIterator_advance(self, n)

    def __eq__(self, x):
        return _dist_tree_api.SwigPyIterator___eq__(self, x)

    def __ne__(self, x):
        return _dist_tree_api.SwigPyIterator___ne__(self, x)

    def __iadd__(self, n):
        return _dist_tree_api.SwigPyIterator___iadd__(self, n)

    def __isub__(self, n):
        return _dist_tree_api.SwigPyIterator___isub__(self, n)

    def __add__(self, n):
        return _dist_tree_api.SwigPyIterator___add__(self, n)

    def __sub__(self, *args):
        return _dist_tree_api.SwigPyIterator___sub__(self, *args)
    def __iter__(self):
        return self
SwigPyIterator_swigregister = _dist_tree_api.SwigPyIterator_swigregister
SwigPyIterator_swigregister(SwigPyIterator)

class _string_list(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, _string_list, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, _string_list, name)
    __repr__ = _swig_repr

    def iterator(self):
        return _dist_tree_api._string_list_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _dist_tree_api._string_list___nonzero__(self)

    def __bool__(self):
        return _dist_tree_api._string_list___bool__(self)

    def __len__(self):
        return _dist_tree_api._string_list___len__(self)

    def __getslice__(self, i, j):
        return _dist_tree_api._string_list___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _dist_tree_api._string_list___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _dist_tree_api._string_list___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _dist_tree_api._string_list___delitem__(self, *args)

    def __getitem__(self, *args):
        return _dist_tree_api._string_list___getitem__(self, *args)

    def __setitem__(self, *args):
        return _dist_tree_api._string_list___setitem__(self, *args)

    def pop(self):
        return _dist_tree_api._string_list_pop(self)

    def append(self, x):
        return _dist_tree_api._string_list_append(self, x)

    def empty(self):
        return _dist_tree_api._string_list_empty(self)

    def size(self):
        return _dist_tree_api._string_list_size(self)

    def swap(self, v):
        return _dist_tree_api._string_list_swap(self, v)

    def begin(self):
        return _dist_tree_api._string_list_begin(self)

    def end(self):
        return _dist_tree_api._string_list_end(self)

    def rbegin(self):
        return _dist_tree_api._string_list_rbegin(self)

    def rend(self):
        return _dist_tree_api._string_list_rend(self)

    def clear(self):
        return _dist_tree_api._string_list_clear(self)

    def get_allocator(self):
        return _dist_tree_api._string_list_get_allocator(self)

    def pop_back(self):
        return _dist_tree_api._string_list_pop_back(self)

    def erase(self, *args):
        return _dist_tree_api._string_list_erase(self, *args)

    def __init__(self, *args):
        this = _dist_tree_api.new__string_list(*args)
        try:
            self.this.append(this)
        except Exception:
            self.this = this

    def push_back(self, x):
        return _dist_tree_api._string_list_push_back(self, x)

    def front(self):
        return _dist_tree_api._string_list_front(self)

    def back(self):
        return _dist_tree_api._string_list_back(self)

    def assign(self, n, x):
        return _dist_tree_api._string_list_assign(self, n, x)

    def resize(self, *args):
        return _dist_tree_api._string_list_resize(self, *args)

    def insert(self, *args):
        return _dist_tree_api._string_list_insert(self, *args)

    def reserve(self, n):
        return _dist_tree_api._string_list_reserve(self, n)

    def capacity(self):
        return _dist_tree_api._string_list_capacity(self)
    __swig_destroy__ = _dist_tree_api.delete__string_list
    __del__ = lambda self: None
_string_list_swigregister = _dist_tree_api._string_list_swigregister
_string_list_swigregister(_string_list)


def DIST_TREE__API_new():
    return _dist_tree_api.DIST_TREE__API_new()
DIST_TREE__API_new = _dist_tree_api.DIST_TREE__API_new

def DIST_TREE__API_set_prefix(handler, prefix):
    return _dist_tree_api.DIST_TREE__API_set_prefix(handler, prefix)
DIST_TREE__API_set_prefix = _dist_tree_api.DIST_TREE__API_set_prefix

def DIST_TREE__API_set_store(handler, store):
    return _dist_tree_api.DIST_TREE__API_set_store(handler, store)
DIST_TREE__API_set_store = _dist_tree_api.DIST_TREE__API_set_store

def DIST_TREE__API_set_branch(handler, branch):
    return _dist_tree_api.DIST_TREE__API_set_branch(handler, branch)
DIST_TREE__API_set_branch = _dist_tree_api.DIST_TREE__API_set_branch

def DIST_TREE__API_load(handler):
    return _dist_tree_api.DIST_TREE__API_load(handler)
DIST_TREE__API_load = _dist_tree_api.DIST_TREE__API_load
# This file is compatible with both classic and new-style classes.


